<?php
/**
 * APIEventLinkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * APIEventLinkTest Class Doc Comment
 *
 * @category    Class */
// * @description APIEventLink
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class APIEventLinkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIEventLink"
     */
    public function testAPIEventLink()
    {
    }

    /**
     * Test attribute "event_link_id"
     */
    public function testPropertyEventLinkId()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "contact_id"
     */
    public function testPropertyContactId()
    {
    }

    /**
     * Test attribute "organisation_id"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "opportunity_id"
     */
    public function testPropertyOpportunityId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "lead_id"
     */
    public function testPropertyLeadId()
    {
    }
}
