<?php
/**
 * ContactDateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Insightly API v2.2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactDateTest Class Doc Comment
 *
 * @category    Class */
// * @description ContactDate
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactDateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactDate"
     */
    public function testContactDate()
    {
    }

    /**
     * Test attribute "date_id"
     */
    public function testPropertyDateId()
    {
    }

    /**
     * Test attribute "occasion_name"
     */
    public function testPropertyOccasionName()
    {
    }

    /**
     * Test attribute "occasion_date"
     */
    public function testPropertyOccasionDate()
    {
    }

    /**
     * Test attribute "repeat_yearly"
     */
    public function testPropertyRepeatYearly()
    {
    }

    /**
     * Test attribute "create_task_yearly"
     */
    public function testPropertyCreateTaskYearly()
    {
    }
}
